### ISSUE TITLE
Snippets Borked After 4.1 Upgrade

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket-gist-plugin#27]
Went from GB 3.8 -> 3.14 - 4.1 and updated this plugin  to 4.0 in the last step.  This worked fine and GB starts with the latest gist plugin no problem.  HOWEVER, when I go to look at a  that looked fine under 3.8 snippet, I see this:

`org.h2.jdbc.JdbcSQLException: Column "X3.ORIGIN_REPOSITORY_NAME" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._6 AS
SELECT
    X3.UPDATED_DATE AS UPDATED_DATE,
    X3.DESCRIPTION AS DESCRIPTION,
    X3.ORIGIN_REPOSITORY_NAME AS ORIGIN_REPOSITORY_NAME,
    X3.ORIGIN_USER_NAME AS ORIGIN_USER_NAME,
    X3.TITLE AS TITLE,
    X3.PRIVATE AS PRIVATE,
    X3.REPOSITORY_NAME AS REPOSITORY_NAME,
    X3.USER_NAME AS USER_NAME,
    X3.REGISTERED_DATE AS REGISTERED_DATE
FROM PUBLIC.GIST X3
WHERE (X3.USER_NAME = ?1)
    AND (X3.PRIVATE = ?2)
ORDER BY =X3.REGISTERED_DATE DESC
LIMIT 10 [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Alias.optimize(Alias.java:51)
	at org.h2.command.dml.Select.prepare(Select.java:835)
	at org.h2.command.Parser.prepare(Parser.java:226)
	at org.h2.engine.Session.prepare(Session.java:426)
	at org.h2.engine.Session.prepare(Session.java:413)
	at org.h2.table.TableView.compileViewQuery(TableView.java:106)
	at org.h2.table.TableView.initColumnsAndTables(TableView.java:151)
	at org.h2.table.TableView.init(TableView.java:102)
	at org.h2.table.TableView.<init>(TableView.java:67)
	at org.h2.table.TableView.createTempView(TableView.java:512)
	at org.h2.command.Parser.readTableFilter(Parser.java:1169)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1873)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1982)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1867)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1688)
	at org.h2.command.Parser.parseSelect(Parser.java:1676)
        .....`

**Comment by tundratim** [comment]
I did a bit more poking about.  If I clone this repo and build the latest plugin - 4.2 - it works fine with a clean install of GitBucket, or seems to. 

The problem shows up when migrating from an older instance of GitBucket.  In my case, I went from 3.8 (everything worked) -> 3.14 (no plugin worked with existing snippets) -> 4.1 (no plugin worked iwth existing snippets).

Any idea on how to make this work?

**Comment by takezoe** [comment]
@tundratim See https://github.com/gitbucket/gitbucket-gist-plugin/issues/28. It might be your help.

**Comment by tundratim** [comment]
Thanks, that looks promising.

**Comment by tundratim** [comment]
Closing because other thread seems to be on this track.
