### ISSUE TITLE
Form too large: xxxxxxx > 200000

### ISSUE THREAD

**Issue by milligramme** [gitbucket/gitbucket-gist-plugin#31]
The error have occurred when i tried to create a snippet with long xsl file.
- os ubuntu 12.04.5 LTS
- gitbucket version 4.2.1
- gist-plugin version 2.0

Can I increase the limit at somewhere?
Thank you.

```
java.lang.IllegalStateException: Form too large: 221236 > 200000
    at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:473)
    at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:411)
    at org.eclipse.jetty.server.Request.extractParameters(Request.java:363)
    at org.eclipse.jetty.server.Request.getParameterMap(Request.java:1003)
    at org.scalatra.servlet.RichRequest.multiParameters(RichRequest.scala:85)
    at org.scalatra.ScalatraBase$$anonfun$14.apply(ScalatraBase.scala:812)
    at org.scalatra.ScalatraBase$$anonfun$14.apply(ScalatraBase.scala:812)
    at scala.Option.getOrElse(Option.scala:121)
    at org.scalatra.ScalatraBase$class.multiParams(ScalatraBase.scala:812)
    at gitbucket.core.controller.ControllerBase.multiParams(ControllerBase.scala:27)
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:176)
    at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
    at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
    at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:27)
    at org.scalatra.ScalatraBase$$anonfun$runFilters$1$$anonfun$apply$6.apply(ScalatraBase.scala:241)
    at org.scalatra.ScalatraBase$$anonfun$runFilters$1$$anonfun$apply$6.apply(ScalatraBase.scala:240)
    at scala.Option.foreach(Option.scala:257)
    at org.scalatra.ScalatraBase$$anonfun$runFilters$1.apply(ScalatraBase.scala:240)
    at org.scalatra.ScalatraBase$$anonfun$runFilters$1.apply(ScalatraBase.scala:239)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at org.scalatra.ScalatraBase$class.runFilters(ScalatraBase.scala:239)
    at gitbucket.core.controller.ControllerBase.runFilters(ControllerBase.scala:27)
    at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:174)
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
    at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
    at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
    at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
    at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
    at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
    at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
    at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
    at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
    at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
    at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
    at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
    at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
    at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
    at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
    at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
    at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
    at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
    at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
    at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
    at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
    at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
    at gitbucket.core.servlet.TransactionFilter.gitbucket$core$servlet$TransactionFilter$$$anonfun$1(TransactionFilter.scala:37)
    at gitbucket.core.servlet.TransactionFilter.gitbucket$core$servlet$TransactionFilter$$$anonfun$1$adapted(TransactionFilter.scala:28)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
    at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
    at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:28)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by milligramme** [comment]
this issue caused by jetty configure form size
