### ISSUE TITLE
Internal server error possibly caused by 4.23.1 update

### ISSUE THREAD

**Issue by bviktor** [gitbucket/gitbucket-gist-plugin#50]
Unfortunately I'm not sure if the 4.23.1 update broke it, all I know is it used to work before (on 4.23), but now if I go to snippets (either top menu, or under a user/group), I get this error:

~~~
Apr 23 22:09:56 code.ad.foobar.com server[67878]: 22:09:56.020 [http-bio-8080-exec-4776] ERROR g.gist.controller.GistController - Catch unhandled error in request: org.apache.catalina.connector.RequestFacade@3fbc0ccf
Apr 23 22:09:56 code.ad.foobar.com server[67878]: java.lang.NoClassDefFoundError: gitbucket/core/model/ReleaseComponent
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.gist.service.GistService.$anonfun$getVisibleGists$1(GistService.scala:17)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.Option.map(Option.scala:146)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.gist.service.GistService.getVisibleGists(GistService.scala:16)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.gist.service.GistService.getVisibleGists$(GistService.scala:15)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.gist.controller.GistController.getVisibleGists(GistController.scala:29)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.gist.controller.GistControllerBase.$anonfun$$init$$1(GistController.scala:52)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:88)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:82)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:81)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.Option.flatMap(Option.scala:171)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:74)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.servlet.PluginControllerFilter.$anonfun$doFilter$2(PluginControllerFilter.scala:42)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.servlet.PluginControllerFilter.$anonfun$doFilter$2$adapted(PluginControllerFilter.scala:35)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.collection.immutable.Stream.foreach(Stream.scala:530)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.servlet.PluginControllerFilter.doFilter(PluginControllerFilter.scala:35)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.Option.getOrElse(Option.scala:121)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.Option.getOrElse(Option.scala:121)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:74)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at java.lang.Thread.run(Thread.java:748)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: Caused by: java.lang.ClassNotFoundException: gitbucket.core.model.ReleaseComponent
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Apr 23 22:09:56 code.ad.foobar.com server[67878]: ... 154 common frames omitted
~~~

Gist plugin is at 4.13.0. Can anyone repro?

**Comment by takezoe** [comment]
I tested and it worked fine in my local environment. Try to once uninstall the plugin and re-install.

**Comment by bviktor** [comment]
Oh, that might be a problem. What's the recommended way to upgrade when you have plugins installed? Is there docs for that?

**Comment by bviktor** [comment]
Yup, a simple uninstall & install solved this :) Do I have to do this after each GitBucket upgrade?

**Comment by bviktor** [comment]
... for all non-default plugins?

**Comment by takezoe** [comment]
When you upgraded GitBucket, all bundled plugins should be upgraded automatically.
If it doesn't happen, it's a bug in GitBucket.

**Comment by bviktor** [comment]
Okay, but snippets (gist) is not a bundled plugin, it was installed manually. Do I have to reinstall all of these after GitBucket upgrades?

**Comment by takezoe** [comment]
Bascally, you don't need it.

But sometimes GitBucket updates contain binary imcompatibility. You have to update some plugins in such case. In addition, Gist plugin is now bundled with GitBucket. So you don't need to install it manually any longer. 😉

**Comment by bviktor** [comment]
Ah, I missed that. Which release added it?

**Comment by takezoe** [comment]
They were added in GitBucket 4.15.0:
http://gitbucket.github.io/gitbucket-news/gitbucket/2017/08/05/gitbucket-4.15.0.html

**Comment by bviktor** [comment]
That's a pretty big oversight on my part, thanks a lot for all the help Takezoe, much appreciated!
